### ISSUE TITLE
Can not install gems from Gemfile on Windows

### ISSUE THREAD

**Issue by jmccann** [test-kitchen/busser-serverspec#24]
The PATH on a Windows guest does not seem to get updated properly so it can not find `bundler` command when trying to install gems from a Gemfile.

Get the following error when trying to install gems from a Gemfile on a Windows guest:

```
-----> Starting Kitchen (v1.4.0.rc.1)
-----> Verifying <default-win-2012r2>...
       Preparing files for transfer
-----> Busser installation detected (busser)
       Installing Busser plugins: busser-serverspec
       Plugin serverspec already installed
       Transferring files to <default-win-2012r2>
-----> Running serverspec test suite
-----> Bundle Installing..
         run  bundle install --gemfile C:\Users\vagrant\AppData\Local\Temp\verifier/suites/serverspec/Gemfile --local || bundle install --gemfile C:\Users\vagrant\AppData\Local\Temp\verifier/suites/serverspec/Gemfile from "."
       C:/opscode/chef/embedded/bin/ruby.exe -IC:/Users/vagrant/AppData/Local/Temp/verifier/suites/serverspec -I'C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/rspec-support-3.2.2/lib';'C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.2.2/lib' 'C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/rspec-core-3.2.2/exe/rspec' --pattern 'C:/Users/vagrant/AppData/Local/Temp/verifier/suites/serverspec/**/*_spec.rb' --color --format documentation --default-path C:/Users/vagrant/AppData/Local/Temp/verifier/suites/serverspec
$$$$$$ C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-serverspec-0.5.4/lib/busser/runner_plugin/serverspec.rb:49:in `run_bundle_install': Use RbConfig instead of obsolete and deprecated Config.
$$$$$$ C:/Users/vagrant/AppData/Local/Temp/verifier/gems/gems/busser-serverspec-0.5.4/lib/busser/runner_plugin/serverspec.rb:49:in `run_bundle_install': Use RbConfig instead of obsolete and deprecated Config.
$$$$$$ 'bundle' is not recognized as an internal or external command,
$$$$$$ operable program or batch file.
$$$$$$ 'bundle' is not recognized as an internal or external command,
$$$$$$ operable program or batch file.
```

**Comment by jmccann** [comment]
FYI, I do have code that seems to fix this that I'm working on submitting as a PR.
