### ISSUE TITLE
Typos in bundle_install

### ISSUE THREAD

**Issue by joerg** [test-kitchen/busser-serverspec#29]
While playing around with system rubies I found, or at least I am pretty sure, a typo in bundle_install [1].
Config::CONFIG['bindir'] should actually be RbConfig::CONFIG['bindir']. I changed it locally and it worked with RbConfig although I am not sure what any of them is supposed to be. Otherwise I get this:
```
-----> Running serverspec test suite
-----> Bundle Installing..
/tmp/verifier/gems/gems/busser-serverspec-0.5.6/lib/busser/runner_plugin/serverspec.rb:50:in `run_bundle_install': uninitialized constant Busser::RunnerPlugin::Serverspec::Config (NameError)
	from /tmp/verifier/gems/gems/busser-serverspec-0.5.6/lib/busser/runner_plugin/serverspec.rb:32:in `test'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:43:in `block in perform'
	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `each'
	from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/command/test.rb:35:in `perform'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `each'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `map'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/group.rb:232:in `dispatch'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:115:in `invoke'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:40:in `block in register'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/command.rb:27:in `run'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor.rb:359:in `dispatch'
	from /tmp/verifier/gems/gems/thor-0.19.0/lib/thor/base.rb:440:in `start'
	from /tmp/verifier/gems/gems/busser-0.7.1/bin/busser:8:in `<top (required)>'
	from /tmp/verifier/gems/bin/busser:23:in `load'
	from /tmp/verifier/gems/bin/busser:23:in `<main>'
```

[1] https://github.com/test-kitchen/busser-serverspec/blob/v0.5.6/lib/busser/runner_plugin/serverspec.rb#L49

**Comment by cl-lab-k** [comment]
How about using `::Config::CONFIG['bindir']` instead of `Config::CONFIG['bindir']`?
BTW, `Config::CONFIG` is obsoleted and deprecated. Using `RbConfig::CONFIG` is better.

**Comment by joerg** [comment]
Sorry, I don't understand the question here. If Config::CONFIG is deprecated in favor of RbConfig::CONFIG, then why not use the new and supported syntax?

Anyways, I tried ::Config::CONFIG and it gave me the same error. System is Fedora 22 in a Docker container and I am using the system ruby which is version 2.2.2.

**Comment by cl-lab-k** [comment]
thank you. Config::CONFIG has been completely removed at ruby 2.2.0 ruby/ruby@011b74b748c0230dc5c013e3a38a9f0d58c5893f
