### ISSUE TITLE
Busser installing newest rspec-core (3.9) where serverspec is using 3.8

### ISSUE THREAD

**Issue by marek-knappe** [test-kitchen/busser-serverspec#62]
```
 Gem::ConflictError:
         Unable to activate rspec-3.8.0, because rspec-core-3.9.0 conflicts with rspec-core (~> 3.8.0)
       # /tmp/verifier/suites/serverspec/xinetd_spec.rb:1:in `<top (required)>'
       # ------------------
       # --- Caused by: ---
       # LoadError:
       #   cannot load such file -- serverspec
       #   /tmp/verifier/suites/serverspec/xinetd_spec.rb:1:in `<top (required)>'
       No examples found.
```

**Comment by grosser** [comment]
can it somehow use the Gemfile we provided instead of doing all the `-I` magic ?

**Comment by grosser** [comment]
hmmm looks like the `-I` things come from rspecs rake task ... can we switch to using `bundle exec rspec` instead ?
